spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?createDatabaseIfNotExist=true
    username: root
    password: Ml22099478
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
